"""Generate plugin skill surfaces from the baseline catalog."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .baseline_catalog import BaselineSkill, load_baseline_catalog

GENERATED_BANNER = (
    "<!-- PLATE-GENERATED:BEGIN skills-surface -->\n"
    "<!-- Do not edit generated skill surfaces manually. -->\n"
    "<!-- Source of truth: src/plate_core/data/baseline_catalog.yml -->\n"
    "<!-- Regenerate: python3 scripts/generate-plugin-skills.py -->\n"
)

GENERATED_FOOTER = "<!-- PLATE-GENERATED:END skills-surface -->\n"

REGENERATE_COMMAND = "python3 scripts/generate-plugin-skills.py"

PLUGIN_SURFACES = ("plugin", ".plugin")


@dataclass(frozen=True)
class PluginSkillsWriteResult:
    written_paths: tuple[Path, ...]
    removed_paths: tuple[Path, ...]


def _format_list(items: tuple[str, ...]) -> str:
    if not items:
        return "_None_"
    return "\n".join(f"- {item}" for item in items)


def render_skills_md(*, regenerate_command: str = REGENERATE_COMMAND) -> str:
    """Render the plugin-level SKILLS.md index from the baseline catalog."""
    catalog = load_baseline_catalog()
    skills = sorted(catalog.skills, key=lambda skill: skill.id)

    lines = [
        GENERATED_BANNER.rstrip(),
        "",
        "# PLATE Baseline Skills",
        "",
        "> **Do not edit this file manually.**",
        f"> Regenerate with: `{regenerate_command}`",
        "",
        "Canonical source: `src/plate_core/data/baseline_catalog.yml`",
        "",
        f"This catalog defines **{len(skills)}** baseline skills used by PLATE agents.",
        "Per-skill plugin payloads live under `skills/<id>/SKILL.md` in the same directory.",
        "",
        "## Index",
        "",
        "| ID | Name | Owning agents |",
        "| --- | --- | --- |",
    ]

    for skill in skills:
        owners = ", ".join(f"`{agent_id}`" for agent_id in skill.owning_agent_ids)
        lines.append(f"| `{skill.id}` | {skill.name} | {owners} |")

    lines.extend(["", "## Details", ""])

    for skill in skills:
        lines.extend(_skill_detail_section(skill))
        lines.append("")

    lines.append(GENERATED_FOOTER.rstrip())
    return "\n".join(lines) + "\n"


def _skill_detail_section(skill: BaselineSkill) -> list[str]:
    owners = ", ".join(f"`{agent_id}`" for agent_id in skill.owning_agent_ids)
    return [
        f"### `{skill.id}` — {skill.name}",
        "",
        skill.description,
        "",
        f"**Owning agents:** {owners}",
        "",
        "**Inputs**",
        "",
        _format_list(skill.inputs),
        "",
        "**Outputs**",
        "",
        _format_list(skill.outputs),
        "",
        "**Examples**",
        "",
        _format_list(skill.examples),
        "",
        f"**Plugin skill file:** `skills/{skill.id}/SKILL.md`",
    ]


def render_skill_md(skill: BaselineSkill, *, regenerate_command: str = REGENERATE_COMMAND) -> str:
    """Render a Grok/Copilot-compatible per-skill SKILL.md payload."""
    owners = ", ".join(skill.owning_agent_ids)
    lines = [
        "---",
        f"name: {skill.name}",
        f"description: {skill.description}",
        "---",
        "",
        GENERATED_BANNER.rstrip(),
        "",
        f"# {skill.name}",
        "",
        f"> Skill id: `{skill.id}`",
        f"> Generated from the baseline catalog. Regenerate with `{regenerate_command}`.",
        "",
        skill.description,
        "",
        f"**Owning agents:** {owners}",
        "",
        "## Inputs",
        "",
        _format_list(skill.inputs),
        "",
        "## Outputs",
        "",
        _format_list(skill.outputs),
        "",
        "## Examples",
        "",
        _format_list(skill.examples),
        "",
        GENERATED_FOOTER.rstrip(),
    ]
    return "\n".join(lines) + "\n"


def expected_plugin_skill_paths(repo_root: Path) -> dict[Path, str]:
    """Return the expected generated files under each plugin surface."""
    catalog = load_baseline_catalog()
    root = repo_root.resolve()
    expected: dict[Path, str] = {}
    skills_md = render_skills_md()
    for surface in PLUGIN_SURFACES:
        base = root / surface
        expected[base / "SKILLS.md"] = skills_md
        for skill in catalog.skills:
            expected[base / "skills" / skill.id / "SKILL.md"] = render_skill_md(skill)
    return expected


def write_plugin_skills_surfaces(
    repo_root: Path,
    *,
    dry_run: bool = False,
) -> PluginSkillsWriteResult:
    """Write generated SKILLS.md and per-skill SKILL.md files to plugin surfaces."""
    root = repo_root.resolve()
    expected = expected_plugin_skill_paths(root)
    written: list[Path] = []
    removed: list[Path] = []

    expected_skill_dirs: set[Path] = set()
    for path in expected:
        if path.name == "SKILL.md":
            expected_skill_dirs.add(path.parent)

    for surface in PLUGIN_SURFACES:
        skills_root = root / surface / "skills"
        if skills_root.is_dir():
            for child in skills_root.iterdir():
                if child.is_dir() and child not in expected_skill_dirs:
                    if dry_run:
                        removed.append(child)
                    else:
                        for nested in sorted(child.rglob("*"), reverse=True):
                            if nested.is_file():
                                nested.unlink()
                            elif nested.is_dir():
                                nested.rmdir()
                        child.rmdir()
                        removed.append(child)

    for path, content in sorted(expected.items(), key=lambda item: str(item[0])):
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        written.append(path)

    return PluginSkillsWriteResult(tuple(written), tuple(removed))


def plugin_skills_surfaces_in_sync(repo_root: Path) -> tuple[bool, list[str]]:
    """Return whether generated plugin skill surfaces match the baseline catalog."""
    root = repo_root.resolve()
    errors: list[str] = []
    expected = expected_plugin_skill_paths(root)

    for path, content in sorted(expected.items(), key=lambda item: str(item[0])):
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            errors.append(f"missing generated file: {rel}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != content:
            errors.append(f"out of date generated file: {rel}")

    for surface in PLUGIN_SURFACES:
        skills_root = root / surface / "skills"
        if not skills_root.is_dir():
            continue
        expected_dirs = {
            (root / surface / "skills" / skill.id).resolve()
            for skill in load_baseline_catalog().skills
        }
        for child in skills_root.iterdir():
            if child.is_dir() and child.resolve() not in expected_dirs:
                errors.append(f"unexpected generated skill directory: {child.relative_to(root).as_posix()}")

    return (not errors, errors)